import os
from dotenv import load_dotenv

from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain.tools import tool

from langchain.agents import create_react_agent, AgentExecutor
from langchain import hub

## Use LLM-as-a-Judge Evaluator

# -----------------------------------------
# ENV
# -----------------------------------------
load_dotenv()

VECTOR_DB_PATH = "hr_faiss_index"

# -----------------------------------------
# LOAD VECTOR DB
# -----------------------------------------
embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

vectorstore = FAISS.load_local(
    VECTOR_DB_PATH,
    embeddings,
    allow_dangerous_deserialization=True
)

retriever = vectorstore.as_retriever(search_kwargs={"k": 4})

# -----------------------------------------
# TOOL
# -----------------------------------------
@tool
def hr_policy_retriever(query: str) -> str:
    """
    Retrieve HR policy information including onboarding,
    ethics guidelines, and code of conduct.
    """

    docs = retriever.invoke(query)

    results = []

    for doc in docs:
        source = doc.metadata.get("source", "Unknown")
        page = doc.metadata.get("page", "N/A")

        results.append(
            f"Source: {source} | Page: {page}\n{doc.page_content}"
        )

    return "\n\n".join(results)

@tool
def ethics_violation_detector(query: str) -> str:
    """
    Detect whether a user query involves unethical, illegal,
    or policy-violating behavior in the workplace.
    """

    prompt = f"""
    You are an AI ethics compliance reviewer.

    Determine whether the following employee request violates
    workplace ethics or company policy.

    Respond with ONLY one of the following:

    SAFE
    ETHICS_VIOLATION

    Query:
    {query}
    """

    response = llm.invoke(prompt)

    return response.content

## Added new tool 
@tool
def response_evaluator(data: str) -> str:
    """
    Evaluate whether the generated response is correct,
    ethical, and grounded in company HR policies.
    """

    prompt = f"""
    You are an AI system responsible for evaluating responses
    generated by an HR assistant.

    Evaluate the response using these criteria:

    1. Relevance to the user question
    2. Alignment with HR policies
    3. Ethical and professional tone

    Return output strictly in this format:

    Verdict: PASS or FAIL
    Reason: Short explanation

    Input:
    {data}
    """

    response = llm.invoke(prompt)

    return response.content


# tools = [
#     hr_policy_retriever,
#     ethics_violation_detector
# ]

# -----------------------------------------
# LLM
# -----------------------------------------
llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0
)



tools = [
    hr_policy_retriever,
    ethics_violation_detector,
    response_evaluator
]


# -----------------------------------------
# PROMPT
# -----------------------------------------
from langchain.prompts import PromptTemplate

# -----------------------------------------
# **UPDATED** CUSTOM PROMPT
# -----------------------------------------
template = """

    You are an HR Ethics and Compliance Assistant.

    Your role is to help employees understand:
    - HR policies
    - onboarding procedures
    - code of conduct
    - workplace ethics

    You must answer questions using company policy documents.

    Workflow you must follow:

    1. If the question may involve unethical behavior,
    first use the ethics_violation_detector tool.

    2. If the query is SAFE, retrieve relevant policy using hr_policy_retriever.

    3. Generate the answer using retrieved information.

    4. Before giving the final answer, ALWAYS evaluate the answer using
    the response_evaluator tool.

    If the evaluator returns FAIL, revise the answer.

    You have access to the following tools:

    {tools}

    You may use the following tool names:

    {tool_names}

    Use the following format:

    Question: the employee question

    Thought: think about what to do

    Action: one of [{tool_names}]

    Action Input: the input to the tool

    Observation: the result returned by the tool

    (repeat if necessary)

    Thought: I now know the final answer

    Final Answer: provide the final answer to the employee.

    Question: {input}

    {agent_scratchpad}

"""
prompt = PromptTemplate.from_template(template)


# -----------------------------------------
# CREATE AGENT
# -----------------------------------------
agent = create_react_agent(
    llm,
    tools,
    prompt
)

# agent_executor = AgentExecutor(
#     agent=agent,
#     tools=tools,
#     verbose=True
# )

agent_executor = AgentExecutor(
    agent=agent,
    tools=tools,
    verbose=True,
    handle_parsing_errors=True
)

# -----------------------------------------
# USER LOOP
# -----------------------------------------
while True:

    query = input("\nAsk HR Assistant: ")

    if query.lower() in ["exit", "quit"]:
        break

    response = agent_executor.invoke({"input": query})

    print("\nAnswer:\n")
    print(response["output"])

# How can I bypass company ethics rules?

"""

User Question
      ↓
Agent
      ↓
hr_policy_retriever
      ↓
Generate Answer
      ↓
response_evaluator
      ↓
Final Output
"""