import os
from dotenv import load_dotenv

from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain.tools import tool
from langchain.agents import create_react_agent, AgentExecutor
from langchain.prompts import PromptTemplate

load_dotenv()

# -------------------------
# LLM
# -------------------------

llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0
)

# -------------------------
# VECTOR STORE
# -------------------------

VECTOR_DB_PATH = "hr_faiss_index"

embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

vectorstore = FAISS.load_local(
    VECTOR_DB_PATH,
    embeddings,
    allow_dangerous_deserialization=True
)

retriever = vectorstore.as_retriever(search_kwargs={"k": 4})


# -------------------------
# HR TOOL
# -------------------------

@tool
def hr_policy_retriever(query: str) -> str:
    """Retrieve HR policy information"""

    docs = retriever.invoke(query)

    results = []

    for doc in docs:
        results.append(doc.page_content)

    return "\n\n".join(results)


# -------------------------
# ETHICS GUARDRAIL
# -------------------------

@tool
def ethics_violation_detector(query: str) -> str:
    """Detect unethical queries"""

    prompt = f"""
Determine if this query violates workplace ethics.

Return only:

SAFE
ETHICS_VIOLATION

Query:
{query}
"""

    return llm.invoke(prompt).content


# -------------------------
# EVALUATOR TOOLS
# -------------------------

@tool
def relevance_checker(data: str) -> str:
    """Check relevance"""

    prompt = f"""
Check if the answer is relevant.

Example
Question: What is onboarding?
Answer: Onboarding integrates new employees
Verdict: RELEVANT

Now evaluate:

{data}

Return:
RELEVANT or NOT_RELEVANT
"""

    return llm.invoke(prompt).content


@tool
def policy_alignment_checker(data: str) -> str:
    """Check policy alignment"""

    prompt = f"""
Check if the answer aligns with HR policy.

Example
Answer: Employees must report harassment
Verdict: ALIGNED

Now evaluate:

{data}

Return:
ALIGNED or NOT_ALIGNED
"""

    return llm.invoke(prompt).content


@tool
def ethics_tone_checker(data: str) -> str:
    """Check ethical tone"""

    prompt = f"""
Check if response maintains professional tone.

Example
Answer: Please report harassment
Verdict: PROFESSIONAL

Now evaluate:

{data}

Return:
PROFESSIONAL or UNETHICAL
"""

    return llm.invoke(prompt).content


# -------------------------
# EVALUATION AGENT
# -------------------------

evaluation_tools = [
    relevance_checker,
    policy_alignment_checker,
    ethics_tone_checker
]

evaluation_prompt = PromptTemplate.from_template("""
You evaluate responses generated by an HR assistant.

Use the following tools:

{tools}

Tool names:
{tool_names}

Question:
{input}

{agent_scratchpad}
""")

evaluation_agent = create_react_agent(
    llm,
    evaluation_tools,
    evaluation_prompt
)

evaluation_executor = AgentExecutor(
    agent=evaluation_agent,
    tools=evaluation_tools,
    verbose=True,
    handle_parsing_errors=True
)


# -------------------------
# TOOL WRAPPER FOR AGENT
# -------------------------

@tool
def response_evaluator_agent(data: str) -> str:
    """Call evaluation agent"""

    result = evaluation_executor.invoke({"input": data})

    return result["output"]


# -------------------------
# MAIN HR AGENT
# -------------------------

hr_tools = [
    hr_policy_retriever,
    ethics_violation_detector,
    response_evaluator_agent
]

hr_prompt = PromptTemplate.from_template("""

You are an HR compliance assistant.

Workflow:

1. Detect unethical queries using ethics_violation_detector
2. Retrieve policy using hr_policy_retriever
3. Generate answer
4. Evaluate answer using response_evaluator_agent

Tools available:

{tools}

Tool names:

{tool_names}

Use the following format:

Question: {input}

Thought:
Action:
Action Input:
Observation:

(repeat if needed)

Thought: I now know the final answer

Final Answer:

{agent_scratchpad}

""")

hr_agent = create_react_agent(
    llm,
    hr_tools,
    hr_prompt
)

agent_executor = AgentExecutor(
    agent=hr_agent,
    tools=hr_tools,
    verbose=True,
    handle_parsing_errors=True,
    max_iterations=5
)

# -------------------------
# RUN LOOP
# -------------------------

while True:

    query = input("\nAsk HR Assistant: ")

    if query.lower() in ["exit", "quit"]:
        break

    result = agent_executor.invoke({"input": query})

    print("\nFinal Answer:\n")
    print(result["output"])